INSERT INTO post (post_title, post_body, attachment, userid)
VALUES
  ('Sample post title 1', 'Sample post body 1', 'http://sampleurl.com/image1.jpg', 3 ),
  ('Sample post title 2', 'Sample post body 2', 'http://sampleurl.com/image2.jpg', 3 ),
  ('Sample post title 3', 'Sample post body 3', 'http://sampleurl.com/image3.jpg', 3 ),
  ('Sample post title 4', 'Sample post body 4', 'http://sampleurl.com/image4.jpg', 3),
  ('Sample post title 5', 'Sample post body 5', 'http://sampleurl.com/image5.jpg', 3 ),
  ('Sample post title 6', 'Sample post body 6', 'http://sampleurl.com/image6.jpg', 3 ),
  ('Sample post title 7', 'Sample post body 7', 'http://sampleurl.com/image7.jpg', 3 ),
  ('Sample post title 8', 'Sample post body 8', 'http://sampleurl.com/image8.jpg', 3 ),
  ('Sample post title 9', 'Sample post body 9', 'http://sampleurl.com/image9.jpg', 3 ),
  ('Sample post title 10', 'Sample post body 10', 'http://sampleurl.com/image10.jpg', 3 ),
  ('Sample post title 11', 'Sample post body 11', 'http://sampleurl.com/image11.jpg', 3 ),
  ('Sample post title 12', 'Sample post body 12', 'http://sampleurl.com/image12.jpg', 3 ),
  ('Sample post title 13', 'Sample post body 13', 'http://sampleurl.com/image13.jpg', 3 ),
  ('Sample post title 14', 'Sample post body 14', 'http://sampleurl.com/image14.jpg', 3 ),
  ('Sample post title 15', 'Sample post body 15', 'http://sampleurl.com/image15.jpg', 3 ),
  ('Sample post title 16', 'Sample post body 16', 'http://sampleurl.com/image16.jpg', 3 ),
  ('Sample post title 17', 'Sample post body 17', 'http://sampleurl.com/image17.jpg', 5 ),
  ('Sample post title 18', 'Sample post body 18', 'http://sampleurl.com/image18.jpg', 5 ),
  ('Sample post title 19', 'Sample post body 19', 'http://sampleurl.com/image19.jpg', 5 ),
  ('Sample post title 20', 'Sample post body 20', 'http://sampleurl.com/image20.jpg', 5 ),
  ('Sample post title 21', 'Sample post body 21', 'http://sampleurl.com/image21.jpg', 5 ),
  ('Sample post title 22', 'Sample post body 22', 'http://sampleurl.com/image22.jpg', 5 ),
  ('Sample post title 23', 'Sample post body 23', 'http://sampleurl.com/image23.jpg', 5 ),
  ('Sample post title 24', 'Sample post body 24', 'http://sampleurl.com/image24.jpg', 5 ),
  ('Sample post title 25', 'Sample post body 25', 'http://sampleurl.com/image25.jpg', 5 );
